# Generated by Django 5.1.7 on 2025-04-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_autor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
