# Generated by Django 5.2.1 on 2025-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autore',
        ),
        migrations.AddField(
            model_name='livro',
            name='autores',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
    ]
